baseURL = "https://www.neelc.org/"
languageCode = "en-us"
title = "Neel Chauhan"
theme = "manis"
publishDir = "/var/www/www.neelc.org/"
copyright = "&copy; 2022 Neel Chauhan"
paginate = 10
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
    homepage = "homepage"
    author = "Neel Chauhan"
    description = "Neel's personal website."
    mainSections = ["posts"]
    email = "neel@neelc.org"
    github = "https://github.com/neelchauhan/"
    twitter = "https://twitter.com/_neelc"

[menu]
     [[menu.main]]
        name = "posts"
        url = "/posts/"
	
    [[menu.main]]
        name = "projects"
        url = "/projects"

    [[menu.main]]
        name = "about"
        url = "/about"
