baseURL = "https://www.neelc.org/"
languageCode = "en-us"
title = "Neel Chauhan"
theme = "accessible-minimalism"
publishDir = "/usr/local/www/www.neelc.org/"

[menu]
     [[menu.main]]
        name = "posts"
        url = "/posts/"
	
    [[menu.main]]
        name = "projects"
        url = "/projects"

    [[menu.main]]
        name = "about"
        url = "/about"
