baseURL = "https://www.neelc.org/"
languageCode = "en-us"
title = "Neel Chauhan"
theme = "beautifulhugo"
publishDir = "/var/www/www.neelc.org/"
copyright = "&copy; 2023 Neel Chauhan"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[Params]
  mainSections = ["posts"]
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true

[Author]
  name = "Neel Chauhan"
  website = "neelc.org"
  email = "neel@neelc.org"
  github = "neelchauhan"
  linkedin = "neelc-tor"
  reddit = "FreeBSDfan"
  mastodon = "https://social.monoxide.network/neel"

[menu]
   [[menu.main]]
    name = "posts"
    url = "/posts/"

  [[menu.main]]
    name = "projects"
    url = "/projects"

  [[menu.main]]
    name = "about"
    url = "/about"
